'use client';

import { useState } from 'react';

/**
 * Individual FAQ item component
 */
const FAQItem = ({ 
  question, 
  answer, 
  isOpen, 
  onToggle 
}: {
  question: string;
  answer: string;
  isOpen: boolean;
  onToggle: () => void;
}) => (
  <div className="border-b border-gray-200 last:border-b-0">
    <button
      onClick={onToggle}
      className="w-full px-6 py-6 text-left hover:bg-gray-50 transition-colors duration-200 focus:outline-none focus:bg-gray-50"
    >
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-semibold text-gray-900 pr-4">
          {question}
        </h3>
        <div className={`flex-shrink-0 transition-transform duration-300 ${isOpen ? 'rotate-180' : ''}`}>
          <svg className="w-5 h-5 text-gray-500" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
          </svg>
        </div>
      </div>
    </button>
    
    <div className={`overflow-hidden transition-all duration-300 ease-in-out ${
      isOpen ? 'max-h-96 opacity-100' : 'max-h-0 opacity-0'
    }`}>
      <div className="px-6 pb-6">
        <p className="text-gray-600 leading-relaxed">
          {answer}
        </p>
      </div>
    </div>
  </div>
);

/**
 * Main FAQ section component
 */
export default function FAQSection() {
  const [openIndex, setOpenIndex] = useState<number | null>(null);
  
  const faqs = [
    {
      question: "What is crypto arbitrage?",
      answer: "Crypto arbitrage is the practice of buying and selling the same cryptocurrency on different exchanges to profit from price differences. PoolMind's automated system continuously monitors multiple exchanges, identifies profitable opportunities, and executes trades instantly to capture these price discrepancies for our investors."
    },
    {
      question: "Is my STX locked?",
      answer: "No, your STX is never locked. You can withdraw your funds at any time by redeeming your PLMD tokens. There are no lock-up periods, minimum holding requirements, or withdrawal restrictions. Your investment remains liquid and accessible whenever you need it."
    },
    {
      question: "How is NAV calculated?",
      answer: "Net Asset Value (NAV) is calculated by dividing the total value of all assets in the pool by the number of outstanding PLMD tokens. This includes the current market value of all cryptocurrencies held, plus any pending trades and accrued profits, minus operational expenses. NAV is updated in real-time as market conditions change."
    },
    {
      question: "What are PLMD tokens?",
      answer: "PLMD tokens represent your proportional share in the PoolMind arbitrage fund. When you deposit STX, you receive PLMD tokens that track the performance of the entire pool. As the fund generates profits through arbitrage trading, the value of your PLMD tokens increases accordingly."
    },
    {
      question: "Can I withdraw anytime?",
      answer: "Yes, you can withdraw your investment at any time with no restrictions. Simply redeem your PLMD tokens through our platform, and you'll receive your proportional share of the fund's current value in STX. Withdrawals are typically processed within minutes during normal market conditions."
    },
    {
      question: "What fees does PoolMind charge?",
      answer: "PoolMind operates on a performance-based fee structure. We only charge a small percentage of the profits generated by successful arbitrage trades. There are no management fees, deposit fees, or withdrawal fees. You only pay when the fund is profitable, aligning our interests with yours."
    },
    {
      question: "How secure is the platform?",
      answer: "Security is our top priority. All funds are secured by audited smart contracts on the Stacks blockchain. We use multi-signature wallets, implement strict security protocols, and undergo regular security audits. Your private keys remain under your control, and all transactions are transparent and verifiable on-chain."
    },
    {
      question: "What returns can I expect?",
      answer: "While past performance doesn't guarantee future results, our arbitrage engine has historically generated consistent returns by capitalizing on market inefficiencies. Returns vary based on market conditions and available arbitrage opportunities. You can track real-time performance through our dashboard and Telegram updates."
    }
  ];
  
  const handleToggle = (index: number) => {
    setOpenIndex(openIndex === index ? null : index);
  };
  
  return (
    <section className="py-20 bg-white">
      <div className="container mx-auto px-4">
        {/* Section header */}
        <div className="text-center mb-16">
          <h2 className="text-4xl md:text-5xl font-bold text-gray-900 mb-6">
            Frequently Asked Questions
          </h2>
          <p className="text-xl text-gray-600 max-w-3xl mx-auto leading-relaxed">
            Get answers to common questions about PoolMind's arbitrage platform and how it works.
          </p>
        </div>

        {/* FAQ accordion */}
        <div className="max-w-4xl mx-auto">
          <div className="bg-white rounded-2xl shadow-lg border border-gray-100 overflow-hidden">
            {faqs.map((faq, index) => (
              <FAQItem
                key={index}
                question={faq.question}
                answer={faq.answer}
                isOpen={openIndex === index}
                onToggle={() => handleToggle(index)}
              />
            ))}
          </div>
        </div>

        {/* Bottom CTA */}
        <div className="text-center mt-16">
          <div className="bg-gradient-to-r from-blue-50 to-indigo-50 rounded-2xl p-8 max-w-2xl mx-auto">
            <h3 className="text-2xl font-bold text-gray-900 mb-4">
              Still have questions?
            </h3>
            <p className="text-gray-600 mb-6">
              Join our Telegram community or reach out to our support team for personalized assistance.
            </p>
            <div className="flex flex-col sm:flex-row gap-4 justify-center">
              <button className="inline-flex items-center px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-xl transition-colors duration-200">
                <svg className="w-5 h-5 mr-2" fill="currentColor" viewBox="0 0 24 24">
                  <path d="M11.944 0A12 12 0 0 0 0 12a12 12 0 0 0 12 12 12 12 0 0 0 12-12A12 12 0 0 0 12 0a12 12 0 0 0-.056 0zm4.962 7.224c.1-.002.321.023.465.14a.506.506 0 0 1 .171.325c.016.093.036.306.02.472-.18 1.898-.962 6.502-1.36 8.627-.168.9-.499 1.201-.82 1.23-.696.065-1.225-.46-1.9-.902-1.056-.693-1.653-1.124-2.678-1.8-1.185-.78-.417-1.21.258-1.91.177-.184 3.247-2.977 3.307-3.23.007-.032.014-.15-.056-.212s-.174-.041-.249-.024c-.106.024-1.793 1.14-5.061 3.345-.48.33-.913.49-1.302.48-.428-.008-1.252-.241-1.865-.44-.752-.245-1.349-.374-1.297-.789.027-.216.325-.437.893-.663 3.498-1.524 5.83-2.529 6.998-3.014 3.332-1.386 4.025-1.627 4.476-1.635z"/>
                </svg>
                Join Telegram
              </button>
              <button className="inline-flex items-center px-6 py-3 border-2 border-gray-300 hover:border-gray-400 text-gray-700 hover:text-gray-900 font-semibold rounded-xl transition-colors duration-200">
                <svg className="w-5 h-5 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M3 8l7.89 5.26a2 2 0 002.22 0L21 8M5 19h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v10a2 2 0 002 2z" />
                </svg>
                Contact Support
              </button>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
